name: Build PowerShell EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Force -Scope CurrentUser

    - name: Generate EXE
      run: |
        Invoke-ps2exe ./randomWallpaper.ps1 ./randomWallpaper.exe

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: wallpaper-exe
        path: randomWallpaper.exe

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: randomWallpaper.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
